sudo: false
language: node_js
node_js:
  - "4"
  - "5.11.0"
  - "6"

# Need to specify a GCC compiler now!
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm prune
  - npm set progress=false

install:
  - npm install --quiet

before_script:

script:
  - npm test

after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - u_glow@hotmail.com

