sudo: false
language: node_js

node_js:
  - '10'

install:
  - npm install

before_script:

script:
  - npm run verify
  - npm run test

after_success:
  - npm run upload-coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - u_glow@hotmail.com
