instrumentation:
  root: lib/
check:
  global:
    statements: 90
    branches: 80
    functions: 80
    lines: 90
  each:
    statements: 72
    functions: 50
    branches: 72
    lines: 72

reporting:
  print: both
  dir: reports/
  reports:
    - cobertura
    - html
    - lcovonly
    - html
    - json
  report-config:
    cobertura: {file: cobertura/coverage.xml}
    json: {file: json/coverage.json}
    lcovonly: {file: lcov/lcov.info}
    text: {file: null}
